### ISSUE TITLE
Fix layout for the forbidden pairs

### ISSUE THREAD

**Issue by Ignition** [Ignition/anon-gift-swop#2]
Currently the central divider `|` isn't central

![image](https://github.com/user-attachments/assets/0093a49b-d78d-438b-8cf8-8f42037969cf)

**Comment by nayasinghania** [comment]
Hi! I can work on this issue!

**Comment by Ignition** [comment]
@raspberri05, thank you for your contribution. I know it is more than what was originally described, but any chance you can provide sensible alignment for the names in the same PR?
![image](https://github.com/user-attachments/assets/89796df1-dc55-4c5f-af1e-43203e1b37b2)

**Comment by nayasinghania** [comment]
yep! will get to work on that

**Comment by nayasinghania** [comment]
done
![image](https://github.com/user-attachments/assets/b9dd633f-7341-4808-9838-bfd050362fd6)

**Comment by nayasinghania** [comment]
added it to the same pr
