### ISSUE TITLE
Add to the README.md

### ISSUE THREAD

**Issue by Ignition** [Ignition/anon-gift-swop#4]
- [x] Describe the project
- [x] FAQ
  - [x] why the British spelling `swop`
- [x] Contribution guide

**Comment by samadshaikh0** [comment]
Hi @Ignition I am new to Github contributions. Can I work on this?

**Comment by nayasinghania** [comment]
Hi! I am an open source contributor and would love to work on this

**Comment by nayasinghania** [comment]
added the changes in pr #5

**Comment by Ignition** [comment]
@samadshaikh0 a PR has already been made and merged for this issue. If you think more should be added to our README, please feel free to propose a contribution via a PR.
